#! /usr/bin/env node

'use strict';

var bean = require('./bean');

bean.then(function(client) {
    client.watch('lampercy', function(err, numwatched) {});
    client.ignore('default', function(err, numwatched) {});
    client.reserve(function(err, jobid, payload) {
        var seed = JSON.parse(payload);
    });
});
